# Cleanup
install.packages("openxlsx")
install.packages("tidyverse")
library("openxlsx")
library("tidyverse")

df <- read.xlsx("ESFA_CONSUMPTION_DASHBOARD_FORMAT.xlsx")
dim(df) # 307084 x 97 dataset
colnames(df) # display all col names
interesting_columns <- c(
    "SurveyscountryDESC",
    "SurveystartyearID",
    "PopulationGroupL2DESC",
    "ExposurehierarchyL1DESC",
    "ExposurehierarchyL2DESC",
    "ExposurehierarchyL3DESC",
    "ExposurehierarchyL4DESC",
    "ExposurehierarchyL5DESC",
    "ExposurehierarchyL6DESC",
    "ExposurehierarchyL7DESC",
    "Metrics",
    "con_days",
    "count_days_s_pg",
    "count_days_wg",
    "count_subject_s_pg",
    "count_subject_wg",
    "per_customer",
    "avg_chronic",
    "avg_chronic_rs",
    "avg_chronic_bw",
    "avg_chronic_bw_rs",
    "STD_CH",
    "STD_CH_RS",
    "STD_CH_BW",
    "STD_CH_BW_RS",
    "p5_chronic",
    "p5_chronic_rs",
    "p5_chronic_bw",
    "p5_chronic_bw_rs",
    "p10_chronic",
    "p10_chronic_rs",
    "p10_chronic_bw",
    "p10_chronic_bw_rs",
    "median_chronic",
    "median_chronic_rs",
    "median_chronic_bw",
    "median_chronic_bw_rs",
    "p95_chronic",
    "p95_chronic_rs",
    "p95_chronic_bw",
    "p95_chronic_bw_rs",
    "p975_chronic",
    "p975_chronic_rs",
    "p975_chronic_bw",
    "p975_chronic_bw_rs",
    "p99_chronic",
    "p99_chronic_rs",
    "p99_chronic_bw",
    "p99_chronic_bw_rs",
    "avg_acute",
    "avg_acute_rs",
    "avg_acute_bw",
    "avg_acute_bw_rs",
    "STD_AC",
    "STD_AC_BW_RS",
    "STD_AC_RS",
    "STD_AC_BW",
    "p5_acute",
    "p5_acute_rs",
    "p5_acute_bw",
    "p5_acute_bw_rs",
    "p10_acute",
    "p10_acute_rs",
    "p10_acute_bw",
    "p10_acute_bw_rs",
    "median_acute",
    "median_acute_rs",
    "median_acute_bw",
    "median_acute_bw_rs",
    "p95_acute",
    "p95_acute_rs",
    "p95_acute_bw",
    "p95_acute_bw_rs",
    "p975_acute",
    "p975_acute_rs",
    "p975_acute_bw",
    "p975_acute_bw_rs",
    "p99_acute",
    "p99_acute_rs",
    "p99_acute_bw",
    "p99_acute_bw_rs",
    "level"
)

df <- select(df, interesting_columns)

# Generate correlations
