name: PANDOC
on: [push]
jobs:
  build:
    name: PANDOC
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: docker://pandoc/core:2.9
          with:
              args: "-d pandoc_def.yml"
        - uses: meeDamian/github-release@2.0
          with:
            tag: v0.1
            token: ${{ secrets.GITHUB_TOKEN }}
            files: release/main.pdf
